apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: jayacs185/backstage-template-test
    backstage.io/code-coverage: scm-only
#     dev.azure.com/project-repo: DevOps Practice/Backstage-template
    backstage.io/techdocs-ref: dir:.
#     backstage.io/managed-by-origin-location: url: 
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}
