apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    # dev.azure.com/project-slug: BUnonprofitandedu/DevOps Practice 
    backstage.io/code-coverage: scm-only
    dev.azure.com/project-repo: DevOps Practice/Backstage-template
    backstage.io/techdocs-ref: dir:.
    backstage.io/managed-by-origin-location: url:https://dev.azure.com/BUnonprofitandedu/DevOps%20Practice/_git/Backstage-template?path=/skeleton/catalog-info.yaml
spec:
  type: website
  lifecycle: experimental
  owner: ${{values.owner | dump}}
